language: node_js
node_js:
  - 8
  - 6
script: npm test
branches:
  only:
    - master
    - /^v[0-9]/
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: Vl8phnCSv7w5qwPSSImGjd5gf0jB/mv8w9rA7lfAouUqqmWeoigeTGxGFWVeQ/3U85OgLEUnolaWG4o+9FmiLVHucyqY4j4knv+hLbEkmOwuC+fHeSHPQ7NFim+41t7sYLizi/gnrbilMl+xPlAriUs5Lh/uHLtSLRIcrR6vcc4f6OqJTqy8CxxLn1Pby96mZ4D2PQGLX3T09urx0r1Kt0xD29BRp2gvZhE0piKweocQpCnBiVzofz/Q07CRv4pkumdKR95bEDytjET6SjI+V0JS8NLFqR81iQhFkYXDgTDY27iEL2KBnPfJBD2IR6XO6Q/OT+UQz5TcrlGILSBsClZRozbXcXpd2NZTkWPbTUtlr9ti0+myH3N4nQnD4z/cBs8ou1DXDhNmOvG0irViiDRgGG8gHj1WrIeh8JUFz6Ovm1FXyThdg3mP9aPDkS7xWUO0W7iurfB/xW2ODOucVxvAq+0i66uuU1vA2xJsfHVngvV0nmJEfpx/FQlRfVwFAHKIjTwXubkDaBv60E6dfuFJEJr1X/vWgZE6Qss17Sq++EZEEN9NySTG7P7cF0UREj+51PRILAL4npFbgFA5H5JovPqWpkwRNEDcgjoH0f6CUMqao16UohlqyYUxnJ8DnpXB1zPKWsgtqcfCl0B+Bal7uZMhgkHS9O6M71cxjUI=
  on:
    tags: true
    node: 8
